version: "3.8"

services:
  bot:
    image: karithamdocker/go-waifubot:latest
    restart: always
    container_name: WaifuBot
    volumes:
      - "./config.yml:/home/waifubot/config.yml"
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    container_name: WaifuDB
    volumes:
      - "/data/db:/data/db"
    ports:
      - "27017:27017"
