// Code generated by go-mockgen 1.1.2; DO NOT EDIT.

package discord

import (
	"sync"

	anilist "github.com/Karitham/WaifuBot/service/anilist"
)

// MockMangaSearcher is a mock implementation of the mangaSearcher interface
// (from the package github.com/Karitham/WaifuBot/discord) used for unit
// testing.
type MockMangaSearcher struct {
	// MangaFunc is an instance of a mock function object controlling the
	// behavior of the method Manga.
	MangaFunc *MangaSearcherMangaFunc
}

// NewMockMangaSearcher creates a new mock of the mangaSearcher interface.
// All methods return zero values for all results, unless overwritten.
func NewMockMangaSearcher() *MockMangaSearcher {
	return &MockMangaSearcher{
		MangaFunc: &MangaSearcherMangaFunc{
			defaultHook: func(string) ([]anilist.Media, error) {
				return nil, nil
			},
		},
	}
}

// surrogateMockMangaSearcher is a copy of the mangaSearcher interface (from
// the package github.com/Karitham/WaifuBot/discord). It is redefined here
// as it is unexported in the source package.
type surrogateMockMangaSearcher interface {
	Manga(string) ([]anilist.Media, error)
}

// NewMockMangaSearcherFrom creates a new mock of the MockMangaSearcher
// interface. All methods delegate to the given implementation, unless
// overwritten.
func NewMockMangaSearcherFrom(i surrogateMockMangaSearcher) *MockMangaSearcher {
	return &MockMangaSearcher{
		MangaFunc: &MangaSearcherMangaFunc{
			defaultHook: i.Manga,
		},
	}
}

// MangaSearcherMangaFunc describes the behavior when the Manga method of
// the parent MockMangaSearcher instance is invoked.
type MangaSearcherMangaFunc struct {
	defaultHook func(string) ([]anilist.Media, error)
	hooks       []func(string) ([]anilist.Media, error)
	history     []MangaSearcherMangaFuncCall
	mutex       sync.Mutex
}

// Manga delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockMangaSearcher) Manga(v0 string) ([]anilist.Media, error) {
	r0, r1 := m.MangaFunc.nextHook()(v0)
	m.MangaFunc.appendCall(MangaSearcherMangaFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the Manga method of the
// parent MockMangaSearcher instance is invoked and the hook queue is empty.
func (f *MangaSearcherMangaFunc) SetDefaultHook(hook func(string) ([]anilist.Media, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Manga method of the parent MockMangaSearcher instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *MangaSearcherMangaFunc) PushHook(hook func(string) ([]anilist.Media, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *MangaSearcherMangaFunc) SetDefaultReturn(r0 []anilist.Media, r1 error) {
	f.SetDefaultHook(func(string) ([]anilist.Media, error) {
		return r0, r1
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *MangaSearcherMangaFunc) PushReturn(r0 []anilist.Media, r1 error) {
	f.PushHook(func(string) ([]anilist.Media, error) {
		return r0, r1
	})
}

func (f *MangaSearcherMangaFunc) nextHook() func(string) ([]anilist.Media, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *MangaSearcherMangaFunc) appendCall(r0 MangaSearcherMangaFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of MangaSearcherMangaFuncCall objects
// describing the invocations of this function.
func (f *MangaSearcherMangaFunc) History() []MangaSearcherMangaFuncCall {
	f.mutex.Lock()
	history := make([]MangaSearcherMangaFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// MangaSearcherMangaFuncCall is an object that describes an invocation of
// method Manga on an instance of MockMangaSearcher.
type MangaSearcherMangaFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []anilist.Media
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c MangaSearcherMangaFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c MangaSearcherMangaFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}
