// Code generated by go-mockgen 1.1.2; DO NOT EDIT.

package discord

import (
	"sync"

	anilist "github.com/Karitham/WaifuBot/service/anilist"
)

// MockUserSearcher is a mock implementation of the userSearcher interface
// (from the package github.com/Karitham/WaifuBot/discord) used for unit
// testing.
type MockUserSearcher struct {
	// UserFunc is an instance of a mock function object controlling the
	// behavior of the method User.
	UserFunc *UserSearcherUserFunc
}

// NewMockUserSearcher creates a new mock of the userSearcher interface. All
// methods return zero values for all results, unless overwritten.
func NewMockUserSearcher() *MockUserSearcher {
	return &MockUserSearcher{
		UserFunc: &UserSearcherUserFunc{
			defaultHook: func(string) ([]anilist.User, error) {
				return nil, nil
			},
		},
	}
}

// surrogateMockUserSearcher is a copy of the userSearcher interface (from
// the package github.com/Karitham/WaifuBot/discord). It is redefined here
// as it is unexported in the source package.
type surrogateMockUserSearcher interface {
	User(string) ([]anilist.User, error)
}

// NewMockUserSearcherFrom creates a new mock of the MockUserSearcher
// interface. All methods delegate to the given implementation, unless
// overwritten.
func NewMockUserSearcherFrom(i surrogateMockUserSearcher) *MockUserSearcher {
	return &MockUserSearcher{
		UserFunc: &UserSearcherUserFunc{
			defaultHook: i.User,
		},
	}
}

// UserSearcherUserFunc describes the behavior when the User method of the
// parent MockUserSearcher instance is invoked.
type UserSearcherUserFunc struct {
	defaultHook func(string) ([]anilist.User, error)
	hooks       []func(string) ([]anilist.User, error)
	history     []UserSearcherUserFuncCall
	mutex       sync.Mutex
}

// User delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockUserSearcher) User(v0 string) ([]anilist.User, error) {
	r0, r1 := m.UserFunc.nextHook()(v0)
	m.UserFunc.appendCall(UserSearcherUserFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the User method of the
// parent MockUserSearcher instance is invoked and the hook queue is empty.
func (f *UserSearcherUserFunc) SetDefaultHook(hook func(string) ([]anilist.User, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// User method of the parent MockUserSearcher instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *UserSearcherUserFunc) PushHook(hook func(string) ([]anilist.User, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *UserSearcherUserFunc) SetDefaultReturn(r0 []anilist.User, r1 error) {
	f.SetDefaultHook(func(string) ([]anilist.User, error) {
		return r0, r1
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *UserSearcherUserFunc) PushReturn(r0 []anilist.User, r1 error) {
	f.PushHook(func(string) ([]anilist.User, error) {
		return r0, r1
	})
}

func (f *UserSearcherUserFunc) nextHook() func(string) ([]anilist.User, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *UserSearcherUserFunc) appendCall(r0 UserSearcherUserFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of UserSearcherUserFuncCall objects describing
// the invocations of this function.
func (f *UserSearcherUserFunc) History() []UserSearcherUserFuncCall {
	f.mutex.Lock()
	history := make([]UserSearcherUserFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// UserSearcherUserFuncCall is an object that describes an invocation of
// method User on an instance of MockUserSearcher.
type UserSearcherUserFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []anilist.User
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c UserSearcherUserFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c UserSearcherUserFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}
