// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package store

import (
	"context"
)

const createUser = `-- name: createUser :exec
INSERT INTO users (user_id)
VALUES ($1)
`

func (q *Queries) createUser(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.createUserStmt, createUser, userID)
	return err
}

const getChar = `-- name: getChar :one
SELECT user_id, id, image, name, date, type
FROM characters
WHERE id = $1
    AND characters.user_id = $2
`

type getCharParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) getChar(ctx context.Context, arg getCharParams) (Character, error) {
	row := q.queryRow(ctx, q.getCharStmt, getChar, arg.ID, arg.UserID)
	var i Character
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Image,
		&i.Name,
		&i.Date,
		&i.Type,
	)
	return i, err
}

const getChars = `-- name: getChars :many
SELECT user_id, id, image, name, date, type
FROM characters
WHERE characters.user_id = $1
`

func (q *Queries) getChars(ctx context.Context, userID int64) ([]Character, error) {
	rows, err := q.query(ctx, q.getCharsStmt, getChars, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.Image,
			&i.Name,
			&i.Date,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const giveChar = `-- name: giveChar :one
UPDATE characters
SET "type" = 'TRADE',
    "user_id" = $1
WHERE characters.id = $2
    AND characters.user_id = $3
RETURNING user_id, id, image, name, date, type
`

type giveCharParams struct {
	Given int64 `json:"given"`
	ID    int64 `json:"id"`
	Giver int64 `json:"giver"`
}

func (q *Queries) giveChar(ctx context.Context, arg giveCharParams) (Character, error) {
	row := q.queryRow(ctx, q.giveCharStmt, giveChar, arg.Given, arg.ID, arg.Giver)
	var i Character
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Image,
		&i.Name,
		&i.Date,
		&i.Type,
	)
	return i, err
}

const insertChar = `-- name: insertChar :exec
INSERT INTO characters ("id", "user_id", "image", "name", "type")
VALUES ($1, $2, $3, $4, $5)
`

type insertCharParams struct {
	Image  string `json:"image"`
	Name   string `json:"name"`
	Type   string `json:"type"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) insertChar(ctx context.Context, arg insertCharParams) error {
	_, err := q.exec(ctx, q.insertCharStmt, insertChar,
		arg.ID,
		arg.UserID,
		arg.Image,
		arg.Name,
		arg.Type,
	)
	return err
}
