name: Build Image

on:
  push:

jobs:
  build-containers:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      BOT_IMAGE_TAG: ${GITHUB_REF##*/}
      OTC_IMAGE_TAG: otc_${GITHUB_REF##*/}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: karitham
          password: ${{ secrets.GR_PAT }}

      - name: setup
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.18/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

      - name: Earthly version
        run: earthly --version

      - name: Run build
        run: |
          earthly --push +docker --BOT_IMAGE_TAG=${GITHUB_REF##*/}
          earthly --push +docker-otc --OTC_IMAGE_TAG=otc_${GITHUB_REF##*/}
